namespace MoneyBack.Web.Services;

/// <summary>
/// Cada emoji con las palabras en español con que la gente lo buscaría.
///
/// Generado desde las anotaciones oficiales de Unicode (CLDR, es.xml), no
/// escrito a mano: una lista propia siempre se queda corta —"Colombia" no
/// encontraba la bandera, "perro" sí, y la diferencia era solo que a mí se
/// me ocurrió una y no la otra.
///
/// Formato: "emoji|palabra palabra palabra". Se guardan hasta seis palabras
/// por emoji, las más cortas, porque las largas son frases descriptivas que
/// nadie teclea y acá el peso se descarga en cada visita.
/// </summary>
public static class EmojisDatos
{
    public static readonly string[] Entradas =
    [
        "0⃣|cero tecla",
        "1⃣|uno tecla",
        "2⃣|dos tecla",
        "3⃣|tres tecla",
        "4⃣|tecla cuatro",
        "5⃣|cinco tecla",
        "6⃣|seis tecla",
        "7⃣|siete tecla",
        "8⃣|ocho tecla",
        "9⃣|nueve tecla",
        "©|simbolo copyright",
        "®|marca simbolo registrada",
        "‐|raya guion menos",
        "–|corto guion semimenos",
        "—|raya guion largo",
        "―|raya barra guion linea horizontal",
        "‘|simples comillas apostrofo izquierdo",
        "’|derecho simples comillas apostrofo",
        "‚|bajo bajas derecho comillas apostrofo",
        "“|dobles apertura comillas izquierdas",
        "”|cierre dobles alemanas comillas derechas",
        "„|bajas dobles alemanas apertura comillas derechas",
        "†|cruz daga signo obelisco",
        "‡|cruz daga doble signo obelisco",
        "•|bolo topo punto vineta boliche",
        "…|puntos elipsis omision suspensivos",
        "‧|con raya guion punto union",
        "‰|mil por tanto",
        "′|prima",
        "″|doble prima",
        "‴|prima triple",
        "‸|insercion circunflejo intercalacion",
        "※|marca japones asterisco omejirushi referencia",
        "‼|doble sorpresa puntuacion exclamacion",
        "‽|exclarrogativo",
        "‾|raya linea vinculum superpuesta",
        "⁂|asterismo asteriscos",
        "⁄|barra trazo fraccion",
        "⁉|exclamacion interrogacion",
        "⁻|menos superindice",
        "₢|brb moneda cruceiro",
        "₣|franco moneda frances",
        "₤|lira moneda",
        "₥|milesima milesimo",
        "₨|rupia moneda",
        "₩|kpw krw won",
        "€|eur euro divisa moneda",
        "₰|aleman moneda penique",
        "₱|peso",
        "₳|ara moneda austral",
        "₶|libra moneda tornesa",
        "₷|moneda spesmilo",
        "₹|india rupia divisa moneda",
        "₽|rublo divisa moneda",
        "₿|btc bitcoin",
        "℗|sonido copyright grabacion",
        "™|marca simbolo comercial",
        "ℹ|informacion",
        "←|hacia flecha apuntar apuntando izquierda",
        "↑|hacia arriba flecha apuntar apuntando",
        "→|hacia flecha apuntar derecha apuntando",
        "↓|abajo hacia flecha apuntar apuntando",
        "↔|flecha derecha direccion izquierda",
        "↕|abajo arriba flecha direccion",
        "↖|hacia arriba flecha esquina noroeste superior",
        "↗|hacia arriba flecha derecha esquina noreste",
        "↘|abajo hacia flecha derecha esquina sudeste",
        "↙|abajo hacia flecha esquina inferior suroeste",
        "↚|hacia flecha tachada izquierda",
        "↛|hacia flecha derecha tachada",
        "↜|onda hacia flecha izquierda",
        "↝|onda hacia flecha derecha",
        "↞|doble hacia punta flecha izquierda",
        "↟|doble hacia punta arriba flecha",
        "↠|doble hacia punta flecha derecha",
        "↡|abajo doble hacia punta flecha",
        "↢|con cola hacia flecha izquierda",
        "↣|con cola hacia flecha derecha",
        "↤|barra desde hacia flecha izquierda",
        "↥|barra desde hacia arriba flecha",
        "↦|barra desde hacia flecha derecha",
        "↧|abajo barra desde hacia flecha",
        "↨|con base abajo arriba flecha",
        "↩|curva flecha derecha direccion izquierda curvandose",
        "↪|curva flecha derecha direccion izquierda curvandose",
        "↫|con bucle hacia flecha izquierda",
        "↬|con bucle hacia flecha derecha",
        "↭|onda hacia flecha derecha izquierda",
        "↮|hacia flecha derecha tachada izquierda",
        "↯|abajo hacia flecha zigzag",
        "↰|con hacia punta arriba flecha izquierda",
        "↱|con hacia punta arriba flecha derecha",
        "↲|con abajo hacia punta flecha izquierda",
        "↳|con abajo hacia punta flecha derecha",
        "↴|con abajo hacia angulo flecha derecha",
        "↵|con abajo hacia angulo flecha izquierda",
        "↶|hacia flecha superior izquierda semicirculo",
        "↷|hacia flecha derecha superior semicirculo",
        "↸|con barra hacia larga flecha noroeste",
        "↹|con barra hacia sobre flecha derecha",
        "↺|con flecha abierto circulo sentido antihorario",
        "↻|con flecha abierto circulo horario sentido",
        "↼|con arpon hacia punta arriba izquierda",
        "↽|con abajo arpon hacia punta izquierda",
        "↾|con arpon hacia punta arriba derecha",
        "↿|con arpon hacia punta arriba izquierda",
        "⇀|con arpon hacia punta arriba derecha",
        "⇁|con abajo arpon hacia punta derecha",
        "⇂|con abajo arpon hacia punta derecha",
        "⇃|con abajo arpon hacia punta izquierda",
        "⇄|hacia sobre flecha derecha izquierda",
        "⇅|abajo hacia arriba flecha apuntar flechas",
        "⇆|hacia sobre flecha apuntar derecha flechas",
        "⇇|hacia pareja flechas izquierda",
        "⇈|hacia arriba pareja flechas",
        "⇉|hacia pareja derecha flechas",
        "⇊|abajo hacia pareja flechas",
        "⇋|arpon hacia sobre derecha izquierda",
        "⇌|arpon hacia sobre derecha izquierda",
        "⇍|doble hacia flecha tachada izquierda",
        "⇎|doble hacia flecha derecha tachada izquierda",
        "⇏|doble hacia flecha derecha tachada",
        "⇐|doble hacia flecha izquierda",
        "⇑|doble hacia arriba flecha",
        "⇒|doble hacia flecha derecha",
        "⇓|abajo doble hacia flecha",
        "⇔|doble hacia flecha derecha izquierda",
        "⇖|doble hacia flecha noroeste",
        "⇗|doble hacia flecha nordeste",
        "⇘|doble hacia flecha sudeste",
        "⇙|doble hacia flecha sudoeste",
        "⇚|hacia flecha triple izquierda",
        "⇛|hacia flecha triple derecha",
        "⇜|hacia flecha ondulada izquierda",
        "⇝|hacia flecha derecha ondulada",
        "⇞|con doble hacia arriba flecha tachado",
        "⇟|con abajo doble hacia flecha tachado",
        "⇠|hacia flecha izquierda discontinua",
        "⇡|hacia arriba flecha discontinua",
        "⇢|hacia flecha derecha discontinua",
        "⇣|abajo hacia flecha discontinua",
        "⇤|con barra hacia flecha izquierda",
        "⇥|con barra hacia flecha derecha",
        "⇦|hacia hueca flecha izquierda",
        "⇧|hacia hueca arriba flecha",
        "⇨|hacia hueca flecha derecha",
        "⇩|abajo hacia hueca flecha",
        "⇪|barra desde hacia hueca arriba flecha",
        "⇵|abajo hacia arriba flecha izquierda",
        "∀|para todo universal cualquiera",
        "∂|parcial derivada diferencial",
        "∃|existe",
        "∅|vacio conjunto matematicas",
        "∆|triangulo incremento",
        "∇|nabla triangulo",
        "∈|miembro conjunto contiene elemento",
        "∉|elemento",
        "∋|como miembro contiene elemento",
        "∎|fin qed lqqd prueba",
        "∏|ario logica producto",
        "∑|aria sumativa matematicas",
        "−|menos resta signo restar",
        "∓|mas menos",
        "∕|barra trazo division",
        "∗|operador asterisco",
        "∘|grado anillo volada operador",
        "∙|bolo operador",
        "√|base raiz sordo radical cuadrada",
        "∝|proporcional proporcionalidad",
        "∞|signo infinito",
        "∟|recto angulo matematicas",
        "∠|agudo angulo",
        "∣|divide divisor",
        "∥|paralelo",
        "∧|cuna logica circunflejo",
        "∩|conjunto interseccion",
        "∪|union conjunto coleccion",
        "∫|calculo integral",
        "∬|doble calculo integral",
        "∮|contorno integral",
        "∴|por tanto logica conclusion",
        "∵|logica porque",
        "∶|ratio",
        "∷|proporcion proporcionalidad",
        "∼|tilde operador virgulilla",
        "∽|tilde inversa virgulilla",
        "∾|invertida horizontal",
        "≃|igual asintota matematicas asintoticamente",
        "≅|igual igualdad congruencia isomorfismo matematicas aproximadamente",
        "≈|casi igual aproximado aproximacion",
        "≌|todo igual igualdad matematicas",
        "≒|igual imagen aproximadamente",
        "≖|igual anillo igualdad matematicas",
        "≠|igual inecuacion inecualidad",
        "≡|menu exacto triple identico equivalente hamburguesa",
        "≣|igualdad equivalente matematicas estrictamente",
        "≤|que igual menor inecualidad",
        "≥|que igual mayor inecualidad",
        "≦|que igual menor sobre desigualdad matematicas",
        "≧|que igual mayor sobre desigualdad matematicas",
        "≪|que menor mucho desigualdad matematicas",
        "≫|que mayor mucho desigualdad matematicas",
        "≬|entre",
        "≮|que menor desigualdad matematicas",
        "≯|que mayor desigualdad matematicas",
        "≳|que mayor desigualdad equivalente matematicas",
        "≺|precede matematicas",
        "≻|sucede matematicas",
        "⊁|sucede matematicas",
        "⊂|conjunto subconjunto",
        "⊃|matematicas superconjunto",
        "⊆|igual subconjunto",
        "⊇|igual igualdad matematicas superconjunto",
        "⊕|mas dentro circulo",
        "⊖|menos dentro circulo erosion simetrica diferencia",
        "⊗|por dentro tensor circulo producto",
        "⊘|barra dentro circulo division matematicas",
        "⊙|xnor punto dentro circulo operador",
        "⊚|anillo dentro circulo operador",
        "⊛|dentro circulo operador asterisco",
        "⊞|mas dentro cuadrado matematicas",
        "⊟|menos dentro cuadrado matematicas",
        "⊥|hacia arriba falsum tachuela contradiccion",
        "⊮|fuerza",
        "⊰|precede relacion",
        "⊱|sucede relacion matematicas",
        "⊶|original",
        "⊹|matriz cuadrada conjugada hermitica hermitiana autoadjunta",
        "⊿|triangulo rectangulo matematicas",
        "⋁|aria logica disyuncion",
        "⋂|aria matematicas interseccion",
        "⋃|aria union matematicas",
        "⋅|punto operador",
        "⋆|estrella operador",
        "⋈|union binario natural operador pajarita",
        "⋒|doble matematicas interseccion",
        "⋘|que menor mucho desigualdad matematicas",
        "⋙|que mayor mucho desigualdad matematicas",
        "⋭|como igual grupos normal teoria contiene",
        "⋮|puntos elipsis vertical verticales matematicas suspensivos",
        "⋯|puntos elipsis suspensivos horizontales",
        "⋰|hacia arriba puntos derecha elipsis diagonales",
        "⋱|abajo hacia puntos derecha elipsis diagonales",
        "⌚|reloj",
        "⌛|sin arena reloj tiempo temporizador",
        "⌨|teclado ordenador",
        "⏏|boton expulsar",
        "⏩|doble avance flecha rapido avanzar",
        "⏪|doble flecha rapido izquierda rebobinar retroceso",
        "⏫|doble hacia arriba flecha triangulo",
        "⏬|abajo doble hacia triangulo",
        "⏭|raya pista vertical siguiente triangulos",
        "⏮|atras pista escena anterior triangulo",
        "⏯|pausa triangulo reproducir",
        "⏰|reloj alarma despertador",
        "⏱|reloj cronometro",
        "⏲|reloj temporizador",
        "⏳|con arena reloj tiempo cayendo temporizador",
        "⏸|boton pausa barras vertical",
        "⏹|boton parar detener cuadrado",
        "⏺|boton grabar circulo",
        "Ⓜ|circulo",
        "■|relleno cuadrado",
        "□|hueco cuadrado",
        "▢|con hueco cuadrado esquinas redondeadas",
        "▣|con hueco dentro relleno cuadrado",
        "▤|con rayas relleno cuadrado horizontales",
        "▥|con rayas relleno cuadrado verticales",
        "▦|con relleno cuadrado ortogonal cuadricula",
        "▧|con abajo desde hasta rayas arriba",
        "▨|con abajo desde hasta rayas arriba",
        "▩|con relleno cuadrado diagonal cuadricula",
        "▪|negro pequeno cuadrado geometria",
        "▫|blanco pequeno cuadrado geometria",
        "▬|relleno rectangulo",
        "▭|hueco rectangulo",
        "▮|relleno vertical rectangulo",
        "▰|relleno paralelogramo",
        "▲|hacia arriba flecha relleno apuntando triangulo",
        "△|que hacia hueco apunta arriba triangulo",
        "▴|que hacia apunta arriba pequeno relleno",
        "▵|que hacia hueco apunta arriba pequeno",
        "▶|boton flecha triangulo reproducir reproduccion",
        "▷|que hacia hueco apunta derecha triangulo",
        "▸|que hacia apunta derecha pequeno relleno",
        "▹|que hacia hueco apunta derecha pequeno",
        "►|que hacia apunta derecha puntero relleno",
        "▻|que hacia hueco apunta derecha puntero",
        "▼|abajo hacia flecha relleno apuntando triangulo",
        "▽|que abajo hacia hueco apunta triangulo",
        "▾|que abajo hacia apunta pequeno relleno",
        "▿|que abajo hacia hueco apunta pequeno",
        "◀|izquierda retroceso triangulo",
        "◁|que hacia hueco apunta izquierda triangulo",
        "◂|que hacia apunta pequeno relleno izquierda",
        "◃|que hacia hueco apunta pequeno izquierda",
        "◄|que hacia apunta puntero relleno izquierda",
        "◅|que hacia hueco apunta puntero izquierda",
        "◆|rombo relleno",
        "◇|hueco rombo",
        "◈|con hueco rombo dentro relleno",
        "◉|con ojo pez hueco punto dentro",
        "◊|rombo diamante",
        "○|hueco anillo circulo",
        "◌|circulo punteado",
        "◍|con circulo relleno vertical",
        "◎|diana doble circulo circulos concentricos",
        "●|circulo relleno",
        "◐|con mitad circulo rellena izquierda",
        "◑|con mitad circulo derecha rellena",
        "◒|con mitad circulo rellena inferior",
        "◓|con mitad circulo rellena superior",
        "◔|con circulo derecho relleno superior cuadrante",
        "◕|circulo excepto relleno superior cuadrante izquierdo",
        "◖|relleno izquierdo semicirculo",
        "◗|derecho relleno semicirculo",
        "◘|bolo inverso",
        "◙|con hueco dentro circulo inverso relleno",
        "◜|arco circulo superior cuadrante izquierdo",
        "◝|arco circulo derecho superior cuadrante",
        "◞|arco circulo derecho inferior cuadrante",
        "◟|arco circulo inferior cuadrante izquierdo",
        "◠|superior semicirculo",
        "◡|inferior semicirculo",
        "◢|derecho relleno inferior triangulo",
        "◣|relleno inferior izquierdo triangulo",
        "◤|relleno superior izquierdo triangulo",
        "◥|derecho relleno superior triangulo",
        "◦|bolo hueco",
        "◯|hueco anillo grande circulo",
        "◳|hueco derecho cuadrado superior cuadrante",
        "◷|hueco circulo derecho superior cuadrante",
        "◻|blanco mediano cuadrado geometria",
        "◼|negro mediano cuadrado geometria",
        "◽|blanco mediano pequeno cuadrado geometria",
        "◾|negro mediano pequeno cuadrado geometria",
        "◿|derecho inferior triangulo",
        "☀|sol rayos espacio soleado",
        "☁|nube tiempo",
        "☂|lluvia abierto paraguas",
        "☃|con nieve muneco",
        "☄|cometa espacio espacial meteorito",
        "☎|telefono",
        "☑|con marca casilla seleccion verificacion",
        "☔|con gotas lluvia paraguas",
        "☕|cafe bebida caliente",
        "☘|planta trebol",
        "☝|dedo mano hacia arriba indice apuntar",
        "☠|cara huesos muerte calavera cruzados",
        "☢|senal radiactivo radioactivo radiactividad radioactividad",
        "☣|senal riesgo peligro biologico",
        "☦|cruz ortodoxa religion",
        "☪|luna islam media estrella religion",
        "☮|paz simbolo",
        "☯|yin yang taoismo religion",
        "☸|del rueda dharma budismo religion",
        "☹|con cara ceno fruncido",
        "☺|cara sonrisa contorno relajado sonriente",
        "♀|mujer signo simbolo femenino",
        "♂|signo hombre simbolo masculino",
        "♈|aries carnero zodiaco horoscopo",
        "♉|buey toro tauro zodiaco horoscopo",
        "♊|gemelos geminis zodiaco horoscopo",
        "♋|cancer zodiaco cangrejo horoscopo",
        "♌|leo leon zodiaco horoscopo",
        "♍|virgo zodiaco horoscopo",
        "♎|libra escala balanza zodiaco justicia horoscopo",
        "♏|zodiaco escorpio escorpion horoscopo",
        "♐|arquero zodiaco horoscopo sagitario",
        "♑|cabra zodiaco horoscopo capricornio",
        "♒|agua acuario zodiaco horoscopo",
        "♓|pez piscis pescado zodiaco horoscopo",
        "♟|peon ajedrez",
        "♠|palo carta juego picas",
        "♣|palo carta juego treboles",
        "♥|palo carta juego corazones",
        "♦|palo carta juego diamantes",
        "♨|aguas vapor termas termales",
        "♪|nota musica corchea",
        "♭|nota bemol musica",
        "♯|nota diesis musica sostenido",
        "♻|senal solido simbolo reciclar reciclaje universal",
        "♾|siempre infinito ilimitado universal",
        "♿|senal silla acceso ruedas simbolo",
        "⚒|pico martillo herramienta",
        "⚓|ancla barco gancho",
        "⚔|arma espadas cruzadas",
        "⚕|simbolo asclepio medicina esculapio serpiente",
        "⚖|peso libra balanza zodiaco justicia",
        "⚗|quimica alambique herramienta",
        "⚙|engranaje herramienta",
        "⚛|atomo simbolo",
        "⚜|lis flor",
        "⚠|senal cuidado advertencia",
        "⚡|alto senal peligro voltaje electricidad",
        "⚧|simbolo transgenero",
        "⚪|blanco circulo geometria",
        "⚫|negro circulo geometria",
        "⚰|ataud muerte",
        "⚱|urna muerte funeraria",
        "⚽|balon futbol",
        "⚾|balon pelota beisbol baseball",
        "⛄|sin nieve muneco",
        "⛅|con sol una nube nubes detras",
        "⛈|con nube rayo lluvia trueno",
        "⛎|ofiuco zodiaco portador horoscopo serpiente",
        "⛏|mina pico herramienta",
        "⛑|con una cara cruz ayuda casco",
        "⛓|cadena cadenas",
        "⛓‍💥|rota cadena romper rotura esposas libertad",
        "⛔|senal direccion prohibida prohibido",
        "⛩|japon religion santuario sintoismo sintoista",
        "⛪|cruz iglesia edificio religion cristianismo",
        "⛰|monte montana",
        "⛱|sol arena sombrilla",
        "⛲|fuente",
        "⛳|golf hoyo banderin",
        "⛴|barco ferri ferry",
        "⛵|vela yate barco velero",
        "⛷|esqui nieve persona esquiador esquiando",
        "⛸|hielo patin",
        "⛹|balon botar pelota botando persona",
        "⛹‍♀|balon botar mujer pelota botando",
        "⛹‍♂|balon botar hombre pelota botando",
        "⛺|tienda campana camping vacaciones",
        "⛽|bomba gasolina surtidor combustible",
        "✂|cortar tijeras herramienta",
        "✅|boton marca seleccion verificacion",
        "✈|avion aeroplano",
        "✉|carta sobre correo",
        "✊|alto mano puno cerrado punetazo",
        "✋|esos mano choca cinco levantada",
        "✌|con mano senal victoria",
        "✍|mano lapiz escribir escribiendo",
        "✏|lapiz escolar escribir lapicero",
        "✒|negra pluma tinta escribir boligrafo",
        "✔|marca seleccion verificacion",
        "✖|marca signo cancelar prohibido multiplicacion",
        "✝|cruz latina religion cristianismo",
        "✡|david judio estrella judaismo religion",
        "✨|bengala chispas estrellas",
        "✳|ocho puntas asterisco",
        "✴|ocho puntas estrella",
        "❄|copo frio nieve",
        "❇|chispa",
        "❌|cruz marca tachar tachado cancelar",
        "❎|con cruz boton marca casilla",
        "❓|roja signo pregunta puntuacion interrogacion",
        "❔|blanca pregunta puntuacion interrogacion",
        "❕|blanca puntuacion exclamacion",
        "❗|roja signo puntuacion exclamacion",
        "❣|corazon puntuacion exclamacion",
        "❤|rojo corazon emocion",
        "❤‍🔥|amor fuego llamas pasion corazon lujuria",
        "❤‍🩹|bien mejor salud corazon curarse mejorar",
        "➕|mas suma signo",
        "➖|menos resta signo",
        "➗|signo division",
        "➡|este hacia flecha derecha direccion",
        "➰|giro bucle tirabuzon",
        "➿|bucle doble",
        "⤴|curva hacia arriba flecha derecha direccion",
        "⤵|abajo curva hacia flecha derecha direccion",
        "⨧|dos mas subindice",
        "⨯|vector cruzado producto",
        "⨼|interior producto",
        "⩣|barra doble logica inferior",
        "⩽|con que barra igual menor inclinada",
        "⪍|que igual menor sobre similar",
        "⪚|que doble linea mayor sobre desigualdad",
        "⪺|casi igual signo sobre sucede",
        "⬅|hacia oeste flecha izquierda",
        "⬆|hacia norte arriba flecha direccion",
        "⬇|sur abajo hacia flecha direccion",
        "⬛|negro grande cuadrado geometria",
        "⬜|blanco grande cuadrado geometria",
        "⭐|estelar estrella",
        "⭕|aro rojo hueco circulo",
        "〰|guion largo marca sonido ondulado",
        "〽|marca alternancia",
        "🀄|rojo juego dragon mahjong",
        "🃏|joker comodin",
        "🅰|tipo grupo sanguineo",
        "🅱|tipo grupo sanguineo",
        "🅾|tipo grupo sanguineo",
        "🅿|parking aparcamiento",
        "🆎|tipo grupo sanguineo",
        "🆑|borrar simbolo",
        "🆒|cool mola boton",
        "🆓|free boton gratis simbolo",
        "🆔|simbolo identidad identificacion",
        "🆕|new boton nuevo",
        "🆖|boton nuevo",
        "🆗|boton",
        "🆘|sos ayuda simbolo socorro",
        "🆙|boton arriba novedad simbolo informacion",
        "🆚|boton contra frente versus simbolo",
        "🈁|aqui para japones katakana ideograma",
        "🈂|para japones cortesia katakana ideograma",
        "🈚|para kanji gratis japones ideograma",
        "🈯|para kanji japones ideograma reservado",
        "🈲|para kanji japones ideograma prohibido",
        "🈳|para kanji japones vacante ideograma",
        "🈴|para kanji japones aprobado ideograma",
        "🈵|para kanji lleno japones completo ideograma",
        "🈶|pago para kanji japones ideograma",
        "🈷|para kanji japones mensual cantidad ideograma",
        "🈸|para kanji japones ideograma aplicacion",
        "🈹|para kanji japones descuento ideograma",
        "🈺|para kanji abierto japones ideograma",
        "🉐|para ganga kanji japones ideograma",
        "🉑|para kanji japones aceptable ideograma",
        "🌀|mareo tifon ciclon tornado",
        "🌁|bruma niebla",
        "🌂|lluvia cerrado paraguas accesorios",
        "🌃|noche estrellas estrellada",
        "🌄|sol sobre salida montana amanecer montanas",
        "🌅|del sol salida amanecer",
        "🌆|ciudad paisaje atardecer edificios",
        "🌇|del sol puesta edificios",
        "🌈|lluvia colores arcoiris",
        "🌉|noche puente",
        "🌊|mar ola oceano",
        "🌋|volcan erupcion volcanica",
        "🌌|via lactea espacio galaxia",
        "🌍|globo mundo africa europa tierra planeta",
        "🌎|globo mundo tierra america planeta mostrando",
        "🌏|asia globo mundo tierra planeta australia",
        "🌐|con globo mundo tierra terraqueo meridianos",
        "🌑|luna nueva oscuridad",
        "🌒|luna cuarto espacio creciente",
        "🌓|luna cuarto espacio creciente",
        "🌔|luna gibosa creciente",
        "🌕|luna llena plenilunio",
        "🌖|luna gibosa menguante",
        "🌗|luna cuarto menguante",
        "🌘|luna menguante",
        "🌙|luna espacio creciente",
        "🌚|con cara luna nueva espacio",
        "🌛|con cara luna cuarto espacio creciente",
        "🌜|con cara luna cuarto espacio creciente",
        "🌝|con cara luna llena",
        "🌞|con sol cara brillante",
        "🌟|estrella brillante resplandeciente",
        "🌠|fugaz lluvia estrella",
        "🌡|termometro temperatura",
        "🌤|sol una nube detras pequena",
        "🌥|sol una nube detras grande",
        "🌦|con sol una nube detras lluvia",
        "🌧|con nube lluvia",
        "🌨|con frio nube nieve",
        "🌩|con nube rayo",
        "🌪|nube tornado torbellino",
        "🌫|nube niebla",
        "🌬|cara nube soplar viento",
        "🌭|perrito caliente salchicha",
        "🌮|taco comida mexicano",
        "🌯|mex tex wrap comida burrito mexicano",
        "🌰|seco fruto castana castano",
        "🌱|joven planta planton",
        "🌲|hoja arbol perenne",
        "🌳|hoja arbol caduca caducifolio",
        "🌴|arbol palma palmera",
        "🌵|cactus planta",
        "🌶|chile planta picante",
        "🌷|flor tulipan",
        "🌸|flor cerezo",
        "🌹|flor rosa",
        "🌺|flor hibisco",
        "🌻|sol flor girasol",
        "🌼|flor",
        "🌽|maiz mijo espiga mazorca",
        "🌾|arroz espiga planta",
        "🌿|hoja verde hierba",
        "🍀|hojas cuatro suerte trebol",
        "🍁|arce hoja",
        "🍂|caida hojas caidas",
        "🍃|hoja hojas soplar viento revolotear revoloteando",
        "🍄|seta hongo champinon",
        "🍄‍🟫|seta hongo comida marron vegetal champinon",
        "🍅|fruta tomate verdura ensalada",
        "🍆|fruto verdura berenjena",
        "🍇|uva uvas fruta racimo agracejo",
        "🍈|fruta melon",
        "🍉|fruta sandia",
        "🍊|fruta naranja mandarina",
        "🍋|fruta limon citron citrico",
        "🍋‍🟩|lima fruta citrico tropical",
        "🍌|fruta banana platano",
        "🍍|pina fruta ananas",
        "🍎|poma roja fruta manzana",
        "🍏|poma fruta verde manzana",
        "🍐|pera fruta perilla",
        "🍑|fruta durazno melocoton",
        "🍒|fruta cereza cerezas guindas",
        "🍓|fresa fruta freson",
        "🍔|burger hamburguesa",
        "🍕|pizza porcion restaurante",
        "🍖|con carne hueso restaurante",
        "🍗|muslo pollo restaurante",
        "🍘|arroz galleta",
        "🍙|bola arroz japones onigiri restaurante",
        "🍚|arroz cocido restaurante",
        "🍛|con arroz curry restaurante",
        "🍜|ramen tazon chinos fideos calientes",
        "🍝|pasta espagueti restaurante",
        "🍞|pan molde tostada rebanada",
        "🍟|papas fritas patatas restaurante",
        "🍠|papa asada patata restaurante",
        "🍡|dango pincho postre japones restaurante",
        "🍢|oden pincho japones marisco brocheta",
        "🍣|sushi restaurante",
        "🍤|frita frito gamba restaurante",
        "🍥|comida pastel japones pescado japonesa",
        "🍦|dulce helado cucurucho restaurante",
        "🍧|hielo helado postre raspado hawaiano granizado",
        "🍨|helado postre sorbete",
        "🍩|donut pastel berlina rosquilla",
        "🍪|dulce pasta postre galleta",
        "🍫|barra tableta chocolate restaurante",
        "🍬|dulce chuche caramelo golosina chucheria",
        "🍭|dulce chuche golosina piruleta chucheria",
        "🍮|flan dulce postre pudding",
        "🍯|miel dulce tarro",
        "🍰|tarta trozo pedazo restaurante",
        "🍱|caja bento comida restaurante",
        "🍲|olla comida puchero restaurante",
        "🍳|freir huevo sarten cocinar",
        "🍴|tenedor cuchillo restaurante",
        "🍵|taza tazon bebida",
        "🍶|bar sake tazon bebida botella restaurante",
        "🍷|bar copa vaso vino bebida",
        "🍸|bar copa coctel restaurante",
        "🍹|bar bebida tropical restaurante",
        "🍺|bar jarra cerveza restaurante",
        "🍻|bar jarra jarras cerveza brindando restaurante",
        "🍼|bebe bibe bibi leche biberon botella",
        "🍽|con plato tenedor cuchillo restaurante",
        "🍾|bar cava beber corcho botella descorchada",
        "🍿|maiz palomitas",
        "🎀|lazo celebracion",
        "🎁|regalo envuelto presente envoltorio celebracion",
        "🎂|tarta cumpleanos celebracion",
        "🎃|calabaza linterna halloween celebracion",
        "🎄|abeto arbol navidad celebracion",
        "🎅|noel papa claus feliz padre santa",
        "🎆|fuegos celebracion artificiales",
        "🎇|fuegos bengala celebracion artificiales",
        "🎈|globo celebracion",
        "🎉|canon fiesta confeti celebracion",
        "🎊|bola confeti celebracion",
        "🎋|arbol tanabata festividad celebracion",
        "🎌|japon banderas cruzadas celebracion",
        "🎍|ano pino bambu nuevo japones kadomatsu",
        "🎎|munecas festival japonesas celebracion hinamatsuri",
        "🎏|carpa carpas banderin koinobori celebracion",
        "🎐|furin viento campanilla",
        "🎑|luna tsukimi ceremonia celebracion contemplacion",
        "🎒|colegio escolar mochila",
        "🎓|gorro birrete graduacion celebracion",
        "🎖|medalla militar celebracion",
        "🎗|lazo conmemorativo",
        "🎙|musica estudio microfono",
        "🎚|fader control volumen",
        "🎛|diales musica ruedas control potenciometros",
        "🎞|cine pelicula fotograma",
        "🎟|acceso evento entrada admision entradas",
        "🎠|caballo tiovivo entretenimiento",
        "🎡|feria noria atracciones entretenimiento",
        "🎢|rusa feria parque montana atracciones entretenimiento",
        "🎣|pez cana pesca pescar esparcimiento entretenimiento",
        "🎤|micro karaoke microfono entretenimiento",
        "🎥|cine camara pelicula entretenimiento",
        "🎦|cine pelicula entretenimiento",
        "🎧|cascos auricular",
        "🎨|arte paleta pintor artista pintura",
        "🎩|copa ropa chistera sombrero",
        "🎪|carpa circo entretenimiento",
        "🎫|tique acceso admision",
        "🎬|cine claqueta pelicula entretenimiento",
        "🎭|arte artes teatro mascaras actuacion escenicas",
        "🎮|juego mando videojuego videoconsola",
        "🎯|diana juego blanco",
        "🎰|juego maquina tragaperras",
        "🎱|bola ocho juego negra billar",
        "🎲|dado juego",
        "🎳|bola bolos juego",
        "🎴|flor carta naipe cartas flores japones",
        "🎵|nota musica musical",
        "🎶|notas musica musicales",
        "🎷|saxo musica musical saxofon instrumento",
        "🎸|musica musical guitarra instrumento",
        "🎹|piano musica musical teclado instrumento",
        "🎺|musica musical trompeta instrumento",
        "🎻|musica violin musical instrumento",
        "🎼|musica partitura pentagrama",
        "🎽|con sin banda correr mangas deporte",
        "🎾|tenis pelota deporte",
        "🎿|esqui nieve esquis esquies",
        "🏀|balon canasta deporte baloncesto",
        "🏁|motor bandera cuadros deporte carreras",
        "🏂|nieve snowboard practicante",
        "🏃|carrera deporte maraton persona corriendo",
        "🏃‍♀|mujer correr carrera maraton corriendo",
        "🏃‍♂|correr hombre carrera maraton corriendo",
        "🏄|surf persona surfear haciendo",
        "🏄‍♀|surf mujer surfera haciendo surfista",
        "🏄‍♂|surf hombre surfero haciendo surfista",
        "🏅|premio medalla deportiva",
        "🏆|premio trofeo",
        "🏇|jinete caballo carrera caballos carreras",
        "🏈|balon futbol deporte americano",
        "🏉|balon rugby deporte",
        "🏊|nadar nadando persona natacion",
        "🏊‍♀|mujer nadar nadando",
        "🏊‍♂|nadar hombre nadando",
        "🏋|peso pesas persona levantador levantando halterofilia",
        "🏋‍♀|mujer pesas levantando levantadora halterofilia",
        "🏋‍♂|pesas hombre levantador levantando halterofilia",
        "🏌|golf pelota jugando persona golfista",
        "🏌‍♀|golf mujer jugando jugadora",
        "🏌‍♂|golf hombre jugador jugando",
        "🏍|moto carreras vehiculo motocicleta",
        "🏎|coche carreras",
        "🏏|juego pelota criquet",
        "🏐|balon juego pelota voleibol",
        "🏑|palo juego sobre hierba hockey pelota",
        "🏒|palo disco hielo sobre hockey",
        "🏓|mesa ping pong juego tenis pelota",
        "🏔|con frio nieve montana",
        "🏕|camping acampada campamento vacaciones",
        "🏖|playa sombrilla",
        "🏗|obra edificio construccion",
        "🏘|casas edificio urbanizacion",
        "🏙|ciudad urbano paisaje edificio",
        "🏚|casa vacia abandonada inhabitada deshabitada",
        "🏛|clasico edificio",
        "🏜|arena desierto",
        "🏝|isla desierta",
        "🏞|parque nacional",
        "🏟|estadio",
        "🏠|casa vivienda",
        "🏡|con casa jardin vivienda construccion",
        "🏢|edificio oficinas construccion",
        "🏣|japon correos oficina edificio japonesa",
        "🏤|europa correos europea oficina edificio",
        "🏥|doctor medico edificio hospital medicina",
        "🏦|banca banco edificio",
        "🏧|atm banco senal cajero automatico",
        "🏨|hotel turismo edificio alojamiento",
        "🏩|del amor hotel edificio",
        "🏪|horas tienda edificio comestibles establecimiento",
        "🏫|colegio escuela edificio",
        "🏬|grandes comercio almacenes",
        "🏭|fabrica edificio industria",
        "🏮|roja izakaya lampara japonesa linterna restaurante",
        "🏯|japones castillo construccion",
        "🏰|europeo castillo construccion",
        "🏳|blanca ondear bandera",
        "🏳‍⚧|azul lgtb rosa blanco bandera transgenero",
        "🏳‍🌈|del bandera arcoiris",
        "🏴|negra ondear bandera",
        "🏴‍☠|botin jolly roger pirata tesoro bandera",
        "🏵|flor planta roseta",
        "🏷|etiqueta",
        "🏸|pluma raqueta volante badminton",
        "🏹|arco flecha arquero zodiaco sagitario",
        "🏺|beber jarra anfora acuario zodiaco",
        "🏻|piel tipo tono claro",
        "🏼|piel tipo tono claro medio",
        "🏽|piel tipo tono medio",
        "🏾|piel tipo tono medio oscuro",
        "🏿|piel tipo tono oscuro",
        "🐀|rata roedor",
        "🐁|raton roedor",
        "🐂|buey tauro zodiaco cabestro",
        "🐃|agua bufalo",
        "🐄|res vaca bovino",
        "🐅|tigre felino",
        "🐆|felino leopardo",
        "🐇|conejo gazapo conejito",
        "🐈|gato gatete minino",
        "🐈‍⬛|gato mala negro suerte",
        "🐉|cuento dragon fantasia",
        "🐊|caiman cocodrilo",
        "🐋|ballena cetaceo cachalote",
        "🐌|caracol molusco caracola",
        "🐍|reptil vibora culebra serpiente",
        "🐎|caballo caballos carreras ecuestre",
        "🐏|aries carnero morueco zodiaco",
        "🐐|cabra chivo caprino zodiaco capricornio",
        "🐑|oveja ovino borrego cordero",
        "🐒|mono simio macaco",
        "🐓|ave gallo pollo gallina gallinacea",
        "🐔|ave pollo gallina gallinacea",
        "🐕|perro perrete perrito cachorro",
        "🐕‍🦺|apoyo perro servicio asistencia accesibilidad",
        "🐖|cerdo puerco cochino gorrino",
        "🐗|cerdo jabali salvaje",
        "🐘|elefante paquidermo",
        "🐙|pulpo octopodo cefalopodo",
        "🐚|concha espiral caracola",
        "🐛|bicho gusano insecto",
        "🐜|antenas hormiga insecto",
        "🐝|miel abeja insecto",
        "🐞|insecto mariquita cochinilla",
        "🐟|pez piscis pescado zodiaco pececillo",
        "🐠|pez tropical",
        "🐡|pez globo",
        "🐢|tortuga galapago",
        "🐣|ave huevo pollo pollito cascaron rompiendo",
        "🐤|ave pollo pollito polluelo",
        "🐥|ave pollo frente pollito",
        "🐦|ave pajaro pajarillo",
        "🐦‍⬛|grajo mirlo negro cuervo pajaro",
        "🐦‍🔥|ave fenix fuego renacer fantasia reencarnacion",
        "🐧|ave pinguino",
        "🐨|cara koala marsupial",
        "🐩|perro caniche perrito",
        "🐪|joroba camello desierto dromedario",
        "🐫|camello jorobas desierto bactriano dromedario",
        "🐬|delfin cetaceo",
        "🐭|cara raton",
        "🐮|cara vaca",
        "🐯|cara tigre",
        "🐰|cara conejo mascota",
        "🐱|cara gato mascota",
        "🐲|cara cuento dragon fantasia",
        "🐳|agua chorro ballena soltando",
        "🐴|cara caballo",
        "🐵|cara mono",
        "🐶|cara perro mascota",
        "🐷|cara cerdo gorrino",
        "🐸|cara rana",
        "🐹|cara hamster mascota",
        "🐺|cara lobo",
        "🐻|oso cara",
        "🐻‍❄|oso polar artico blanco",
        "🐼|oso cara panda",
        "🐽|cara cerdo morro nariz",
        "🐾|huellas pezunas",
        "🐿|ardilla",
        "👀|cara ojos",
        "👁|ojo cuerpo",
        "👁‍🗨|ojo texto testigo bocadillo",
        "👂|oreja cuerpo",
        "👃|nariz cuerpo",
        "👄|boca labios",
        "👅|cuerpo lengua",
        "👆|con dedo mano dorso hacia arriba",
        "👇|con dedo mano abajo dorso hacia",
        "👈|con dedo mano dorso indice izquierda",
        "👉|con dedo mano dorso indice derecha",
        "👊|puno cerrado punetazo",
        "👋|mano agitar saludo saludar saludando",
        "👌|con mano senal aprobacion",
        "👍|mano hacia senal arriba pulgar",
        "👎|mano abajo hacia senal pulgar",
        "👏|manos senal palmas aplaudir aplaudiendo",
        "👐|manos abiertas",
        "👑|rey reina corona accesorios complementos",
        "👒|ropa mujer sombrero accesorio",
        "👓|ojo ropa gafas accesorios",
        "👔|ropa corbata accesorio",
        "👕|ropa camiseta",
        "👖|ropa vaqueros pantalones",
        "👗|ropa mujer vestido",
        "👘|ropa kimono japones",
        "👙|bano ropa playa bikini",
        "👚|ropa blusa mujer camisa femenina",
        "👛|cartera monedero accesorios complementos",
        "👜|bolso accesorios complementos",
        "👝|mano bolso cartera accesorios complementos",
        "👞|ropa hombre zapato calzado",
        "👟|ropa tenis correr calzado deportiva zapatilla",
        "👠|mujer tacon zapato",
        "👡|ropa mujer calzado sandalia",
        "👢|bota ropa mujer calzado",
        "👣|pies huellas",
        "👤|busto silueta",
        "👥|dos bustos siluetas",
        "👦|nino joven",
        "👧|nina chica joven",
        "👨|adulto hombre",
        "👨‍⚕|doctor hombre medico enfermero sanitario terapeuta",
        "👨‍⚖|juez fiscal hombre justicia magistrado",
        "👨‍✈|avion vuelo hombre piloto capitan",
        "👨‍🌾|campo hombre granjero labrador agricultor agricultura",
        "👨‍🍳|chef hombre pinche cocinero",
        "👨‍🍼|bebe hombre alimentar amamantar lactancia alimentando",
        "👨‍🎓|hombre graduado estudiante licenciado universitario",
        "👨‍🎤|rock hombre artista cantante estrella",
        "👨‍🎨|hombre paleta pintor artista pinturas",
        "👨‍🏫|hombre docente maestro educador profesor instructor",
        "👨‍🏭|hombre obrero fabrica montaje operario industrial",
        "👨‍💻|hombre tecnologo tecnologia informatico profesional programador",
        "👨‍💼|hombre empresa oficina director ejecutivo oficinista",
        "👨‍🔧|hombre mecanica mecanico operario fontanero profesional",
        "👨‍🔬|fisico hombre biologo ciencia quimico cientifico",
        "👨‍🚀|cohete hombre espacio astronauta",
        "👨‍🚒|camion hombre bombero manguera apagafuegos",
        "👨‍🦯|con ciego baston hombre invidente accesibilidad",
        "👨‍🦼|silla hombre ruedas electrica accesibilidad",
        "👨‍🦽|silla hombre manual ruedas accesibilidad",
        "👩|mujer adulta",
        "👩‍⚕|mujer medica doctora enfermera sanitaria sanitario",
        "👩‍⚖|jueza mujer fiscal justicia magistrada",
        "👩‍✈|avion mujer vuelo piloto capitana",
        "👩‍🌾|campo mujer granjera labradora agricultora agricultura",
        "👩‍🍳|chef mujer pinche cocinera",
        "👩‍🍼|bebe mujer alimentar amamantar lactancia alimentando",
        "👩‍🎓|mujer graduada estudiante licenciada universitaria",
        "👩‍🎤|rock mujer artista cantante estrella",
        "👩‍🎨|mujer paleta artista pintora pinturas",
        "👩‍🏫|mujer docente maestra educadora profesora instructora",
        "👩‍🏭|mujer obrera fabrica montaje operaria industrial",
        "👩‍💻|mujer tecnologa tecnologia informatica profesional programadora",
        "👩‍💼|mujer empresa oficina directora ejecutiva oficinista",
        "👩‍🔧|mujer mecanica operaria fontanera profesional electricista",
        "👩‍🔬|mujer fisica biologa ciencia quimica cientifica",
        "👩‍🚀|mujer cohete espacio astronauta",
        "👩‍🚒|camion mujera bombera manguera apagafuegos",
        "👩‍🦯|con ciega mujer baston invidente accesibilidad",
        "👩‍🦼|mujer silla ruedas electrica accesibilidad",
        "👩‍🦽|mujer silla manual ruedas accesibilidad",
        "👪|familia",
        "👫|mano mujer hombre novios pareja",
        "👬|gays mano novios pareja hombres",
        "👭|mano novias pareja mujeres lesbianas",
        "👮|agente policia personas",
        "👮‍♀|poli mujer agente policia",
        "👮‍♂|poli agente hombre policia",
        "👯|con bailar conejo fiesta orejas personas",
        "👯‍♀|con mujer bailar conejo fiesta orejas",
        "👯‍♂|con bailar conejo fiesta hombre orejas",
        "👰|con boda velo novia persona",
        "👰‍♀|con boda velo mujer novia",
        "👰‍♂|con boda velo novio hombre",
        "👱|rubia rubio adulta rubias rubios persona",
        "👱‍♀|mujer rubia rubiales",
        "👱‍♂|rubio hombre rubiales",
        "👲|con gua mao chino gorro persona",
        "👳|con persona turbante",
        "👳‍♀|con mujer turbante",
        "👳‍♂|con hombre turbante",
        "👴|mayor hombre anciano",
        "👵|mayor mujer anciana",
        "👶|bebe nino joven",
        "👷|casco obrero trabajador profesional construccion",
        "👷‍♀|mujer obrera albanila profesional trabajadora construccion",
        "👷‍♂|hombre obrero albanil trabajador profesional construccion",
        "👸|hadas cuento fantasia princesa",
        "👹|oni cara cuento cuernos demonio japones",
        "👺|cara tengu cuento demonio japones fantasia",
        "👻|cara cuento criatura fantasma monstruo",
        "👼|bebe cara angel cuento",
        "👽|cara ovni alien criatura alienigena extraterrestre",
        "👾|cara ovni alien criatura monstruo alienigena",
        "👿|con cara diablo cuernos demonio enfadada",
        "💀|cara cuento muerte calavera monstruo",
        "💁|mano persona mostrador informacion",
        "💁‍♀|mano mujer empleada mostrador informacion",
        "💁‍♂|mano hombre empleado mostrador informacion",
        "💂|real guardia britanica",
        "💂‍♀|mujer guardia vigilante",
        "💂‍♂|hombre guardia vigilante",
        "💃|mujer bailar bailando",
        "💄|barra labios cosmetica maquillaje pintalabios",
        "💅|las unas esmalte manicura pintarse cosmetica",
        "💆|cara salon facial masaje persona recibiendo",
        "💆‍♀|cara mujer salon facial masaje recibiendo",
        "💆‍♂|cara salon facial hombre masaje recibiendo",
        "💇|pelo corte belleza persona peluquero cortandose",
        "💇‍♀|pelo corte mujer belleza peluquero cortandose",
        "💇‍♂|pelo corte hombre belleza peluquero cortandose",
        "💈|poste barbero barberia peluquero",
        "💉|aguja medico jeringa medicina jeringuilla",
        "💊|medico pildora medicina pastilla comprimido",
        "💋|beso marca labios romance",
        "💌|amor carta correo corazon",
        "💍|anillo diamante",
        "💎|gema joya piedra diamante preciosa",
        "💏|beso romance personas",
        "💐|ramo flores bouquet",
        "💑|amor pareja personas enamorada enamoradas",
        "💒|boda iglesia romance celebrando",
        "💓|amor latido corazon emocion latiendo",
        "💔|roto corazon emocion partido",
        "💕|dos amor amantes corazon corazones",
        "💖|amor corazon emocion brillante",
        "💗|latido corazon nervioso creciente emocionado",
        "💘|con amor flecha corazon emocion",
        "💙|azul corazon emocion",
        "💚|verde corazon emocion",
        "💛|corazon emocion amarillo",
        "💜|morado corazon emocion",
        "💝|con san lazo corazon emocion valentin",
        "💞|corazon corazones giratorio giratorios",
        "💟|adorno corazon",
        "💠|con flor rombo petalo geometria",
        "💡|luz idea comic bombilla electricidad",
        "💢|comic enfado simbolo enfadado",
        "💣|bomba comic emocion",
        "💤|zzz comic sueno dormir simbolo",
        "💥|comic colision",
        "💦|comic gotas sudor emocion",
        "💧|agua gota comic sudor",
        "💨|humo comic salir correr carrera corriendo",
        "💩|con caca ojos comic mojon mierda",
        "💪|comic biceps fuerte musculo flexionado",
        "💫|comic mareo emocion simbolo estrella",
        "💬|comic dialogo bocadillo conversacion",
        "💭|comic burbuja bocadillo pensamiento",
        "💮|flor blanca",
        "💯|100 cien pleno puntos",
        "💰|bolsa dinero dolares",
        "💱|cambio dinero divisa moneda divisas",
        "💲|dolar dinero simbolo",
        "💳|credito tarjeta",
        "💴|yen banco dinero billete",
        "💵|banco dolar dinero billete",
        "💶|euro banco dinero billete",
        "💷|banco libra dinero billete",
        "💸|con alas banco dinero billete",
        "💹|alza tabla alcista mercado",
        "💺|plaza silla asiento transporte",
        "💻|personal portatil ordenador",
        "💼|cartera maletin documentos",
        "💽|disco minidisc",
        "💾|disco disquete",
        "💿|disco optico",
        "📀|dvd disco",
        "📁|archivo carpeta archivos",
        "📂|abierta archivo carpeta archivos",
        "📃|pagina doblada documento",
        "📄|hacia arriba pagina anverso documento",
        "📅|fecha calendario",
        "📆|fecha calendario recortable",
        "📇|ficha fichas cartera tarjetas organizador",
        "📈|grafica grafico evolucion tendencia ascendente",
        "📉|grafica grafico evolucion tendencia descendente",
        "📊|barras grafico",
        "📋|pinza tabla papeles portapapeles",
        "📌|tachuela chincheta",
        "📍|redonda chincheta",
        "📎|clip",
        "📏|regla",
        "📐|regla escuadra triangulo triangular",
        "📑|pestanas marcadores",
        "📒|libro cuaderno contabilidad",
        "📓|libreta cuaderno",
        "📔|con tapa cuaderno decoracion decorativa",
        "📕|libro cerrado",
        "📖|libro abierto",
        "📗|libro verde",
        "📘|azul libro",
        "📙|libro naranja",
        "📚|libro libros",
        "📛|nombre etiqueta identificativa",
        "📜|papel pergamino",
        "📝|notas cuaderno comunicacion",
        "📞|telefono auricular comunicacion",
        "📟|busca localizador comunicacion",
        "📠|fax maquina comunicacion",
        "📡|antena satelite comunicacion",
        "📢|mano altavoz comunicacion",
        "📣|megafono comunicacion",
        "📤|correo salida bandeja enviado comunicacion",
        "📥|correo bandeja entrada recibido comunicacion",
        "📦|caja paquete",
        "📧|sobre correo electronico comunicacion",
        "📨|carta sobre correo entrante electronico comunicacion",
        "📩|con carta sobre correo flecha electronico",
        "📪|con buzon vacio bajada bandera cerrado",
        "📫|con buzon bandera cerrado contenido levantada",
        "📬|con buzon abierto bandera contenido levantada",
        "📭|con buzon vacio bajada abierto bandera",
        "📮|buzon cartas correo",
        "📯|posta corneta",
        "📰|diario periodico",
        "📱|movil celular telefono",
        "📲|con una movil flecha llamada recibir",
        "📳|modo movil celular telefono vibracion",
        "📴|movil apagado celular telefono",
        "📵|uso hacer movil moviles llamadas telefono",
        "📶|movil senal antena barras celular telefono",
        "📷|fotos camara",
        "📸|con flash camara",
        "📹|video camara videocamara",
        "📺|television",
        "📻|radio",
        "📼|cinta video",
        "📽|cine pelicula proyector",
        "📿|collar cuentas rosario religion",
        "🔀|cruzado flechas aleatoria reproduccion entrecruzadas",
        "🔁|flechas repetir repeticion",
        "🔂|una uno vez flechas repetir repeticion",
        "🔃|senal flechas horario recarga sentido verticales",
        "🔄|senal flechas recarga sentido direccion antihorario",
        "🔅|bajo senal tenue brillo",
        "🔆|alto senal brillo brillante",
        "🔇|con mute marca altavoz silencio silenciado",
        "🔈|bajo altavoz volumen",
        "🔉|con medio altavoz volumen",
        "🔊|alto altavoz volumen",
        "🔋|pila bateria",
        "🔌|enchufe corriente electrico electricidad",
        "🔍|lupa hacia buscar izquierda orientada",
        "🔎|lupa hacia buscar derecha orientada",
        "🔏|con pluma candado cerrado privacidad estilografica",
        "🔐|llave seguro candado cerrado",
        "🔑|llave contrasena",
        "🔒|cerrar candado cerrado",
        "🔓|abrir abierto candado",
        "🔔|campana",
        "🔕|con ruido signo campana cancelacion",
        "🔖|marcador marcapaginas",
        "🔗|eslabon",
        "🔘|boton opcion",
        "🔙|con back atras flecha izquierda",
        "🔚|con end final flecha izquierda",
        "🔛|con doble punta senal encima flecha",
        "🔜|con soon flecha derecha",
        "🔝|con top hacia arriba flecha",
        "🔞|anos apto para menos menores prohibido",
        "🔠|abcd letras latinas mayusculas",
        "🔡|abcd letras latinas minusculas",
        "🔢|1234 digitos numeros",
        "🔣|simbolos",
        "🔤|abc latino alfabeto",
        "🔥|fuego llama",
        "🔦|luz linterna",
        "🔧|llave inglesa herramienta",
        "🔨|martillo herramienta",
        "🔩|tuerca tornillo herramienta",
        "🔪|arma cocina cocinar cuchillo",
        "🔫|agua verano juguete pistola",
        "🔬|instrumento laboratorio microscopio",
        "🔭|astronomia telescopio instrumento",
        "🔮|bola buena cristal fortuna adivinacion",
        "🔯|seis buena puntas fortuna estrella adivinacion",
        "🔰|para verde japones simbolo amarillo principiante",
        "🔱|ancla emblema tridente",
        "🔲|con borde boton negro cuadrado",
        "🔳|con borde boton blanco cuadrado",
        "🔴|rojo circulo geometria",
        "🔵|azul circulo geometria",
        "🔶|rombo grande naranja geometria",
        "🔷|azul rombo grande geometria",
        "🔸|rombo naranja pequeno geometria",
        "🔹|azul rombo pequeno geometria",
        "🔺|rojo hacia arriba geometria triangulo",
        "🔻|rojo abajo hacia geometria triangulo",
        "🔼|boton hacia arriba triangulo",
        "🔽|abajo boton hacia triangulo",
        "🕉|hindu religion",
        "🕊|ave paz pajaro paloma",
        "🕋|hach islam kaaba umrah musulman religion",
        "🕌|islam mezquita religion",
        "🕍|judaismo religion sinagoga",
        "🕎|menora religion candelabro",
        "🕐|una punto reloj",
        "🕑|dos punto reloj",
        "🕒|tres punto reloj",
        "🕓|punto reloj cuatro",
        "🕔|cinco punto reloj",
        "🕕|seis punto reloj",
        "🕖|punto reloj siete",
        "🕗|ocho punto reloj",
        "🕘|nueve punto reloj",
        "🕙|diez punto reloj",
        "🕚|once punto reloj",
        "🕛|doce punto reloj",
        "🕜|una media reloj",
        "🕝|dos media reloj",
        "🕞|tres media reloj",
        "🕟|media reloj cuatro",
        "🕠|cinco media reloj",
        "🕡|seis media reloj",
        "🕢|media reloj siete",
        "🕣|ocho media reloj",
        "🕤|media nueve reloj",
        "🕥|diez media reloj",
        "🕦|once media reloj",
        "🕧|doce media reloj",
        "🕯|luz vela",
        "🕰|reloj sobremesa",
        "🕳|agujero orificio",
        "🕴|traje levitar persona negocios trajeada levitando",
        "🕵|cara espia detective",
        "🕵‍♀|espia mujer agente detective investigadora",
        "🕵‍♂|espia agente hombre detective investigador",
        "🕶|ojo sol gafas oscuras",
        "🕷|arana insecto",
        "🕸|tela arana telarana",
        "🕹|juego mando palanca joystick videojuego",
        "🕺|bailar hombre bailando",
        "🖇|clips union unidos",
        "🖊|boli escribir boligrafo",
        "🖋|pluma tinta escribir boligrafo estilografica",
        "🖌|pincel pintar",
        "🖍|cera lapiz",
        "🖐|dedo mano abierta",
        "🖕|dedo mano hacia arriba corazon peineta",
        "🖖|mano spock saludo vulcano",
        "🖤|negro corazon",
        "🖥|ordenador sobremesa",
        "🖨|impresora ordenador",
        "🖱|raton ordenador",
        "🖲|bola ordenador trackball desplazamiento",
        "🖼|marco museo cuadro enmarcado",
        "🗂|fichas fichero separador",
        "🗃|caja archivo tarjetas archivador",
        "🗄|oficina archivos archivador organizador",
        "🗑|cubo basura papelera",
        "🗒|bloc notas espiral cuaderno",
        "🗓|espiral calendario",
        "🗜|banco tornillo herramienta",
        "🗝|llave antigua",
        "🗞|papel noticias enrollado periodico",
        "🗡|arma daga punal cuchillo",
        "🗣|cara cabeza hablar silueta parlante",
        "🗨|por burbuja dialogo bocadillo izquierda conversacion",
        "🗯|por rabia cabreo enfado derecha bocadillo",
        "🗳|con urna voto papeleta",
        "🗺|mapa mundo mundial mapamundi",
        "🗻|fuji monte montana naturaleza",
        "🗼|tokio torre",
        "🗽|nyc york nueva estatua libertad",
        "🗾|mapa japon",
        "🗿|moai pascua estatua",
        "😀|cara feliz sonrisa divertido sonriendo",
        "😁|con ojo cara ojos risa sonrisa",
        "😂|cara risa lagrima llorando felicidad",
        "😃|con cara ojos risa grandes divertido",
        "😄|con ojo cara ojos abierta sonrisa",
        "😅|con cara frio risa sudor sonriendo",
        "😆|con los boca cara ojos risa",
        "😇|con cara halo angel aureola sonrisa",
        "😈|con cara cuernos demonio sonrisa sonriendo",
        "😉|ojo cara guino guinando",
        "😊|con ojo cara ojos feliz rubor",
        "😋|cara rico comida hambre delicioso saboreando",
        "😌|cara alivio aliviado",
        "😍|con amor cara ojos corazon sonrisa",
        "😎|con sol cara guay gafas sonriendo",
        "😏|con cara listillo sonriendo superioridad",
        "😐|cara neutral inexpresivo",
        "😑|sin cara expresion inexpresion inexpresiva inexpresivo",
        "😒|cara rechazo desaprobacion insatisfaccion",
        "😓|con cara frio sudor",
        "😔|cara alicaido pensativo desanimada desanimado",
        "😕|cara confuso confusion",
        "😖|cara frustrado frustracion",
        "😗|beso cara besando",
        "😘|beso cara lanzando",
        "😙|con ojo beso cara ojos besando",
        "😚|con los ojo beso cara ojos",
        "😛|cara lengua sacando",
        "😜|ojo cara guino lengua sacando guinando",
        "😝|con ojo cara ojos fuera sabor",
        "😞|cara decepcion decepcionada decepcionado",
        "😟|cara preocupada preocupado preocupacion",
        "😠|cara enfadada enfadado histerico",
        "😡|cara furia cabreo cabreada enfadado",
        "😢|cara llorar triste lagrima llorando",
        "😣|cara desesperada frustracion desesperacion",
        "😤|cara cabreo enfado resoplando",
        "😥|mal cara pero menos triste aliviada",
        "😦|con boca cara ceno abierta fruncido",
        "😧|cara angustia angustiada angustiado",
        "😨|cara miedo miedoso asustada asustado",
        "😩|cara agotada agotado cansado",
        "😪|cara sueno dormir",
        "😫|cara cansada cansado",
        "😬|una cara mueca haciendo",
        "😭|cara fuerte llorar triste lagrima llorando",
        "😮|con boca cara abierta",
        "😮‍💨|cara alivio jadear silbar exhalar bocanada",
        "😯|cara alucinado estupefacta estupefacto sorprendido",
        "😰|con cara frio sudor ansiedad",
        "😱|cara miedo panico asustado gritando",
        "😲|cara pasmado alucinado asombrada asombrado",
        "😳|cara colorado sonrojada sonrojado",
        "😴|zzz cara sueno dormido durmiendo",
        "😵|cara mareo mareada",
        "😵‍💫|con cara ojos mareo espiral mareado",
        "😶|sin boca cara callado silencio",
        "😶‍🌫|las cara entre nubes cabeza niebla",
        "😷|con cara malo medica enfermo mascara",
        "😸|con cara gato ojos sonrisa sonriendo",
        "😹|cara gato risa lagrima llorando",
        "😺|cara gato feliz alegre sonrisa sonriendo",
        "😻|con cara gato ojos corazon enamorado",
        "😼|una cara gato mueca ironico sonrisa",
        "😽|beso cara gato besando carinoso",
        "😾|cara gato enfadado",
        "😿|cara gato pena triste lagrima llorando",
        "🙀|cara gato panico asustado sorpresa preocupacion",
        "🙁|con cara ceno fruncido ligeramente",
        "🙂|cara sonrisa sonriendo ligeramente",
        "🙂‍↔|negar cabeza negando moviendose horizontalmente",
        "🙂‍↕|cabeza asentir asintiendo moviendose verticalmente",
        "🙃|cara reves",
        "🙄|con cara ojos blanco vueltos frustracion",
        "🙅|mano gesto persona haciendo prohibido",
        "🙅‍♀|mano gesto mujer haciendo prohibido",
        "🙅‍♂|mano gesto hombre haciendo prohibido",
        "🙆|mano vale gesto acuerdo persona haciendo",
        "🙆‍♀|mano vale gesto mujer acuerdo haciendo",
        "🙆‍♂|mano vale gesto hombre acuerdo haciendo",
        "🙇|una gesto perdon persona disculpa haciendo",
        "🙇‍♀|una gesto mujer perdon disculpa haciendo",
        "🙇‍♂|una gesto hombre perdon disculpa haciendo",
        "🙈|con los mal cara mono ojos",
        "🙉|con los mal cara mono oidos",
        "🙊|con mal boca cara mono tapada",
        "🙋|con mano feliz gesto persona levantar",
        "🙋‍♀|con mano gesto mujer levantar levantada",
        "🙋‍♂|con mano gesto hombre levantar levantada",
        "🙌|mano gesto hurra manos celebrando levantadas",
        "🙍|ceno gesto persona fruncido frunciendo",
        "🙍‍♀|ceno gesto mujer fruncido frunciendo",
        "🙍‍♂|ceno gesto hombre fruncido frunciendo",
        "🙎|gesto persona haciendo pucheros",
        "🙎‍♀|gesto mujer haciendo pucheros",
        "🙎‍♂|gesto hombre haciendo pucheros",
        "🙏|por mano orar favor manos rezar",
        "🚀|cohete espacio vehiculo",
        "🚁|aspas volar rotores vehiculo helicoptero",
        "🚂|tren vapor vehiculo locomotora",
        "🚃|tren vagon tranvia vehiculo electrico ferrocarril",
        "🚄|ave alta tren rapido velocidad ferrocarril",
        "🚅|bala tren vehiculo velocidad shinkansen",
        "🚆|tren vehiculo ferrocarril",
        "🚇|metro suburbano transporte subterraneo",
        "🚈|tren ligero transporte ferrocarril",
        "🚉|tren estacion",
        "🚊|tranvia trolebus transporte",
        "🚋|vagon tranvia vehiculo",
        "🚌|bus autobus transporte",
        "🚍|autobus proximo vehiculo",
        "🚎|tranvia trolebus transporte",
        "🚏|parada autobus",
        "🚐|bus autobus minibus transporte",
        "🚑|medica vehiculo ambulancia asistencia transporte",
        "🚒|coche fuego camion bomberos vehiculo",
        "🚓|coche policia patrulla vehiculo",
        "🚔|coche policia proximo patrulla vehiculo",
        "🚕|taxi coche vehiculo",
        "🚖|taxi proximo vehiculo",
        "🚗|coche vehiculo automovil",
        "🚘|coche proximo vehiculo automovil",
        "🚙|camping caravana vehiculo deportivo furgoneta utilitario",
        "🚚|camion reparto vehiculo mercancias transporte",
        "🚛|camion trailer vehiculo articulado",
        "🚜|tractor vehiculo agricultura",
        "🚝|tren monorrail monocarril transporte ferrocarril",
        "🚞|montana vehiculo ferrocarril",
        "🚟|vehiculo suspension ferrocarril",
        "🚠|cable montana vehiculo funicular teleferico",
        "🚡|aereo tranvia vehiculo teleferico",
        "🚢|barco vehiculo",
        "🚣|bote remo barca persona remando",
        "🚣‍♀|bote remo barca mujer remando",
        "🚣‍♂|bote remo barca hombre remando",
        "🚤|barco lancha motora vehiculo",
        "🚥|luz senales trafico semaforo horizontal",
        "🚦|luz senales trafico semaforo vertical",
        "🚧|obras senal construccion",
        "🚨|coche luces policia",
        "🚩|bandera triangular informativa localizacion",
        "🚪|puerta",
        "🚫|pasar entrar prohibido prohibicion",
        "🚬|fumar cigarro cigarrillo",
        "🚭|fumar senal prohibido",
        "🚮|usar senal tirar basura papelera",
        "🚯|senal tirar basura prohibido",
        "🚰|agua potable",
        "🚱|agua potable",
        "🚲|bici vehiculo bicicleta",
        "🚳|vehiculo bicicleta prohibido bicicletas prohibidas",
        "🚴|persona ciclismo ciclista bicicleta",
        "🚴‍♀|mujer ciclismo ciclista bicicleta",
        "🚴‍♂|hombre ciclismo ciclista bicicleta",
        "🚵|bike montana persona ciclista mountain bicicleta",
        "🚵‍♀|bike mujer montana ciclista mountain bicicleta",
        "🚵‍♂|bike hombre montana ciclista mountain bicicleta",
        "🚶|andar caminar persona caminando",
        "🚶‍♀|andar mujer marcha caminata caminando",
        "🚶‍♂|andar hombre marcha caminata caminando",
        "🚷|paso senal peaton peatones prohibido",
        "🚸|ninos senal cruzando",
        "🚹|con aseo bano para senal hombre",
        "🚺|con una aseo bano para mujer",
        "🚻|aseos senal servicios",
        "🚼|bebe senal cambiar lactancia",
        "🚽|bano vater inodoro",
        "🚾|aseos lavabo servicios",
        "🚿|agua bano ducha",
        "🛀|bano banera persona",
        "🛁|bano banera",
        "🛂|control pasaportes",
        "🛃|aduana",
        "🛄|maleta equipaje recogida equipajes",
        "🛅|consigna deposito equipaje servicio",
        "🛋|sofa hotel lampara",
        "🛌|cama hotel dormir persona",
        "🛍|bolsa bolsas compra compras",
        "🛎|hotel timbre botones campanilla",
        "🛏|cama hotel dormir",
        "🛐|culto lugar religion",
        "🛑|stop senal parada octagono",
        "🛒|carro compra carrito supermercado",
        "🛕|hindu templo",
        "🛖|casa yurta cabana",
        "🛗|ascensor elevador montacargas accesibilidad",
        "🛘|alud rocas montana peligro desastre avalancha",
        "🛙|luz mar faro guia senal baliza",
        "🛜|red wifi conexion internet inalambrica",
        "🛝|jugar parque tobogan atracciones",
        "🛞|girar rodar rueda circulo neumatico",
        "🛟|rescate flotador seguridad salvavidas socorrista",
        "🛠|llave inglesa martillo herramienta",
        "🛡|escudo defensa",
        "🛢|bidon barril petroleo",
        "🛣|autopista carretera",
        "🛤|via tren",
        "🛥|barco motor vehiculo",
        "🛩|avion avioneta",
        "🛫|avion salida aeroplano despegando",
        "🛬|avion llegada aeroplano aterrizando",
        "🛰|espacio satelite vehiculo",
        "🛳|barco vehiculo pasajeros",
        "🛴|patinete",
        "🛵|moto escuter scooter",
        "🛶|barca barco canoa piragua",
        "🛷|trineo",
        "🛸|ovni volante platillo",
        "🛹|tabla monopatin skateboard",
        "🛺|tuk mototaxi rickshaw",
        "🛻|pickup ranchera camioneta",
        "🛼|patin cuatro ruedas patines",
        "🟠|circulo naranja",
        "🟡|circulo amarillo",
        "🟢|verde circulo",
        "🟣|lila morado circulo purpura",
        "🟤|marron circulo",
        "🟥|rojo cuadrado",
        "🟦|azul cuadrado",
        "🟧|naranja cuadrado",
        "🟨|amarillo cuadrado",
        "🟩|verde cuadrado",
        "🟪|lila morado purpura cuadrado",
        "🟫|marron cuadrado",
        "🟰|igual mates signo grueso igualdad matematicas",
        "🤌|mano dedos gesto hacia arriba italia",
        "🤍|blanco corazon emocion",
        "🤎|marron corazon emocion",
        "🤏|mano poco poquito pellizco pellizcando",
        "🤐|con boca cara cerrada cremallera",
        "🤑|con boca cara dinero lengua",
        "🤒|con cara malo enfermo termometro",
        "🤓|cara friki friqui empollon",
        "🤔|cara duda pensando pensativa",
        "🤕|con cara dolor venda cabeza herida",
        "🤖|cara robot monstruo",
        "🤗|con cara manos abrazo sonrisa abrazando",
        "🤘|dedo mano rock signo cuernos haciendo",
        "🤙|mano gesto llamar pulgar menique haciendo",
        "🤚|mano dorso levantado",
        "🤛|puno hacia izquierda",
        "🤜|puno hacia derecha",
        "🤝|manos acuerdo apreton",
        "🤞|mano dedos cruzar suerte cruzados",
        "🤟|mano gesto quiero",
        "🤠|con cara vaquera vaquero sombrero",
        "🤡|cara payaso",
        "🤢|cara nauseas vomitar",
        "🤣|cara ojos risa cerrados carcajada revolviendose",
        "🤤|baba cara babeando",
        "🤥|cara nariz pinocho mentiroso",
        "🤦|con mano frente persona facepalm incredulidad",
        "🤦‍♀|con mano mujer frente facepalm incredulidad",
        "🤦‍♂|con mano frente hombre facepalm incredulidad",
        "🤧|cara panuelo estornudo estornudar estornudando",
        "🤨|con cara ceja alzada esceptico desconfiado",
        "🤩|con cara sonrisa estrellas sonriendo",
        "🤪|ojo cara loco grande pequeno",
        "🤫|cara callado pidiendo silencio",
        "🤬|con boca cara simbolo maldecir simbolos",
        "🤭|con boca cara mano vaya sobre",
        "🤮|cara malo enfermo vomitar vomitando",
        "🤯|cabeza explosion explotando",
        "🤰|mujer embarazada",
        "🤱|dar bebe pecho materna amamantar lactancia",
        "🤲|hacia arriba juntas palmas oracion",
        "🤳|selfi camara selfie autofoto telefono",
        "🤴|corona principe",
        "🤵|con novio persona esmoquin",
        "🤵‍♀|con mujer esmoquin",
        "🤵‍♂|con hombre esmoquin",
        "🤶|mama noel claus feliz madre santa",
        "🤷|duda hombros persona encogida encogerse indiferencia",
        "🤷‍♀|duda mujer hombros encogida encogerse indiferencia",
        "🤷‍♂|duda hombre hombros encogido encogerse indiferencia",
        "🤸|rueda lateral persona pirueta gimnasia haciendo",
        "🤸‍♀|una dando mujer rueda deporte lateral",
        "🤸‍♂|una dando rueda hombre deporte lateral",
        "🤹|persona haciendo malabares equilibrio malabarismo malabarista",
        "🤹‍♀|mujer haciendo malabares malabarismo malabarista",
        "🤹‍♂|hombre haciendo malabares malabarismo malabarista",
        "🤺|espada esgrima persona haciendo esgrimista",
        "🤼|lucha luchador luchando personas",
        "🤼‍♀|lucha mujer deporte mujeres luchando luchadora",
        "🤼‍♂|lucha hombre deporte hombres luchador luchando",
        "🤽|jugando persona waterpolo waterpolista",
        "🤽‍♀|agua mujer deporte jugando waterpolo waterpolista",
        "🤽‍♂|agua hombre deporte jugando waterpolo waterpolista",
        "🤾|jugando persona balonmano balonmanista",
        "🤾‍♀|mujer deporte jugando balonmano balonmanista",
        "🤾‍♂|hombre deporte jugando balonmano balonmanista",
        "🤿|buzo tubo buceo bucear mascara esnorquel",
        "🥀|flor marchita marchitada marchitarse",
        "🥁|musica tambor baquetas",
        "🥂|copa copas bebida brindar brindis brindando",
        "🥃|copa vaso licor whisky chupito",
        "🥄|cuchara cubiertos cucharilla",
        "🥅|red deporte porteria",
        "🥇|oro medalla primero",
        "🥈|plata medalla segundo",
        "🥉|bronce medalla tercero",
        "🥊|boxeo guante deporte",
        "🥋|judo artes karate uniforme marciales taekwondo",
        "🥌|roca juego piedra curling",
        "🥍|bola palo pelota raqueta lacrosse",
        "🥎|bola pelota softball",
        "🥏|disco frisbee volador",
        "🥐|bollo comida cruasan frances croissant",
        "🥑|fruta comida aguacate",
        "🥒|comida pepino verdura pepinillo",
        "🥓|bacon carne beicon comida panceta",
        "🥔|papa comida patata verdura",
        "🥕|comida verdura zanahoria",
        "🥖|pan barra comida baguete frances baguette",
        "🥗|bol verde comida ensalada",
        "🥘|arroz comida paella",
        "🥙|pan pita durum kebab comida falafel",
        "🥚|huevo comida",
        "🥛|vaso leche bebida",
        "🥜|seco fruto comida verdura cacahuete cacahuetes",
        "🥝|kiwi fruta comida",
        "🥞|dulce comida postre tortita pancakes tortitas",
        "🥟|masa gyoza comida jiaozi dumpling",
        "🥠|fortuna galleta profecia adivinacion supersticion",
        "🥡|caja para llevar recipiente restaurante",
        "🥢|hashi palillos cubiertos",
        "🥣|con cereal cuenco cuchara desayuno",
        "🥤|con vaso zumo pajita refresco",
        "🥥|coco pina colada palmera",
        "🥦|col brocoli repollo",
        "🥧|masa pastel relleno",
        "🥨|salada bretzel galleta pretzel",
        "🥩|carne corte filete chuleta",
        "🥪|bocata sandwich bocadillo emparedado",
        "🥫|lata comida conserva enlatada",
        "🥬|bok col pak choi choy hoja",
        "🥭|fruta mango tropical",
        "🥮|luna otono pastel yuebing festival",
        "🥯|pan bagel bocadillo panaderia",
        "🥰|con amor cara adorar corazones enamorada",
        "🥱|cara sueno bostezo cansado dormido aburrido",
        "🥲|con cara lagrima sonrisa aliviado orgulloso",
        "🥳|cara gorro fiesta capirote celebracion matasuegras",
        "🥴|cara grogui mareado atontado entonado intoxicado",
        "🥵|con cara roja calor golpe sudor",
        "🥶|con cara frio helado congelada congelado",
        "🥷|ninja oculto sigilo furtivo guerrero luchador",
        "🥸|cara gafas nariz careta disfraz disimulo",
        "🥹|las cara llorar triste emocion lagrimas",
        "🥺|por cara ojos favor piedad implorar",
        "🥻|ropa sari prenda vestido",
        "🥼|bata doctor medico cientifico experimento laboratorio",
        "🥽|gafas nadar ocular soldar proteccion",
        "🥾|bota camping mochilero senderismo",
        "🥿|zapato calzado bailarina",
        "🦀|animal cancer zodiaco cangrejo",
        "🦁|leo cara leon zodiaco",
        "🦂|zodiaco escorpio escorpion",
        "🦃|ave pavo",
        "🦄|cara unicornio",
        "🦅|ave aguila",
        "🦆|ave pato",
        "🦇|vampiro murcielago",
        "🦈|pez tiburon",
        "🦉|ave buho pajaro lechuza",
        "🦊|cara zorro",
        "🦋|bonito insecto mariposa",
        "🦌|bambi ciervo cervatillo",
        "🦍|simio gorila primate",
        "🦎|reptil lagarto lagartija",
        "🦏|paquidermo rinoceronte",
        "🦐|gamba comida camaron marisco langostino",
        "🦑|comida calamar molusco",
        "🦒|jirafa manchas",
        "🦓|raya cebra",
        "🦔|puas erizo espinas",
        "🦕|sauropodo diplodocus brontosaurio braquiosaurio",
        "🦖|rex tiranosaurio",
        "🦗|grillo saltamontes",
        "🦘|salto saltar canguro marsupial",
        "🦙|lana llama alpaca vicuna guanaco",
        "🦚|ave pavo real plumas orgulloso",
        "🦛|hipopotamo paquidermo",
        "🦜|ave loro hablar pirata papagayo",
        "🦝|astuto ladino ojeras curioso mapache maquillaje",
        "🦞|pinzas marisco langosta bogavante",
        "🦟|virus fiebre insecto malaria mosquito",
        "🦠|ameba virus germen bacteria microbio",
        "🦡|miel ratel tejon melero",
        "🦢|ave feo cisne patito",
        "🦣|mamut lanudo colmillo extinguido",
        "🦤|ave dodo dronte pajaro mauricio extinguido",
        "🦥|vago lento gandul perezoso",
        "🦦|pesca nutria bromista jugueton",
        "🦧|mono simio primate orangutan",
        "🦨|mal olor tufo hedor peste mofeta",
        "🦩|flamenco tropical ostentoso extravangante",
        "🦪|buceo ostra perla",
        "🦫|castor roedor",
        "🦬|bufalo cibolo bisonte",
        "🦭|foca leon marino",
        "🦮|guia ciego perro invidente lazarillo accesibilidad",
        "🦯|ciega ciego baston ceguera invidente accesibilidad",
        "🦰|pelo rojo rojizo pelirrojo",
        "🦱|afro pelo rizo bucle rizado tirabuzon",
        "🦲|sin bola pelo calvo billar afeitado",
        "🦳|cana gris pelo viejo blanco",
        "🦴|hueso esqueleto",
        "🦵|patada pierna extremidad",
        "🦶|pie patada pisoton",
        "🦷|molar muela diente dentista",
        "🦸|bien heroe heroina personaje superheroe superpoder",
        "🦸‍♀|heroe mujer bondad heroina superheroe superpoder",
        "🦸‍♂|bueno heroe hombre superheroe superpoder superhombre",
        "🦹|mal villana villano personaje superpoder supervillana",
        "🦹‍♀|mal mujer malvada villana supervillana",
        "🦹‍♂|mal hombre malvado villano supervillano",
        "🦺|chaleco seguridad emergencia",
        "🦻|con oreja sordo audifono auditiva protesis",
        "🦼|silla ruedas electrica accesibilidad",
        "🦽|silla manual ruedas accesibilidad",
        "🦾|brazo mecanico protesis ortopedia accesibilidad",
        "🦿|pierna mecanica protesis ortopedia accesibilidad",
        "🧀|cuna queso trozo",
        "🧁|dulce cupcake magdalena reposteria",
        "🧂|sal salero condimento",
        "🧃|zumo brick carton envase tetrabrik",
        "🧄|ajo vampiro condimento",
        "🧅|llorar cebolla condimento",
        "🧆|falafel garbanzo albondiga",
        "🧇|gofre waffle",
        "🧈|lacteo mantequilla",
        "🧉|mate bebida infusion",
        "🧊|frio hielo cubito iceberg",
        "🧋|tea boba leche perla bubble burbuja",
        "🧌|trol hadas cuento fantasia monstruo",
        "🧍|pie persona levantada levantado levantarse",
        "🧍‍♀|pie mujer levantada levantarse",
        "🧍‍♂|pie hombre levantado levantarse",
        "🧎|persona rodillas arrodillada arrodillado arrodillarse",
        "🧎‍♀|mujer rodillas arrodillada arrodillarse",
        "🧎‍♂|hombre rodillas arrodillado arrodillarse",
        "🧏|oir oido sorda persona sordera escuchar",
        "🧏‍♀|mujer sorda sordera",
        "🧏‍♂|sordo hombre sordera",
        "🧐|con cara estirado monoculo aristocratico",
        "🧑|adulta genero neutro persona",
        "🧑‍⚕|salud doctor medico enfermero sanitario terapeuta",
        "🧑‍⚖|juez fiscal juicio magistrado",
        "🧑‍✈|avion vuelo piloto capitan",
        "🧑‍🌾|granjero labrador jardinero agricultor cultivador agricultura",
        "🧑‍🍳|chef pinche cocinero cocinillas guisandero",
        "🧑‍🍼|bebe persona alimentar amamantar lactancia alimentando",
        "🧑‍🎄|noel claus feliz santa cuento fiestas",
        "🧑‍🎓|graduado estudiante licenciado universitario",
        "🧑‍🎤|rock artista cantante estrella",
        "🧑‍🎨|paleta pintor artista pinturas",
        "🧑‍🏫|docente maestro educador profesor ensenanza instructor",
        "🧑‍🏭|obrero fabrica montaje operario industrial trabajador",
        "🧑‍💻|software tecnologo tecnologia informatico profesional programador",
        "🧑‍💼|empresa director ejecutivo arquitecto oficinista",
        "🧑‍🔧|tecnico mecanica mecanico operario fontanero profesional",
        "🧑‍🔬|fisico biologo ciencia quimico cientifico profesional",
        "🧑‍🚀|cohete espacio astronauta",
        "🧑‍🚒|camion bombero manguera",
        "🧑‍🤝‍🧑|dos mano pareja persona personas",
        "🧑‍🦯|con ciego baston persona invidente accesibilidad",
        "🧑‍🦼|silla ruedas persona electrica accesibilidad",
        "🧑‍🦽|silla manual ruedas persona accesibilidad",
        "🧑‍🧑‍🧒|nino adulto familia",
        "🧑‍🧑‍🧒‍🧒|nino adulto familia",
        "🧑‍🧒|nino adulto familia",
        "🧑‍🧒‍🧒|nino adulto familia",
        "🧑‍🩰|ballet bailarin bailarina",
        "🧒|crio joven genero neutro infante",
        "🧓|mayor adulto genero maduro neutro persona",
        "🧔|con barba barbas barbudo persona",
        "🧔‍♀|barba mujer",
        "🧔‍♂|barba hombre",
        "🧕|con hiyab mujer panuelo",
        "🧖|una sauna vapor persona",
        "🧖‍♀|una mujer sauna vapor",
        "🧖‍♂|una sauna vapor hombre",
        "🧗|persona alpinista escalador escalando",
        "🧗‍♀|mujer alpinista escalando escaladora",
        "🧗‍♂|hombre alpinista escalador escalando",
        "🧘|loto yoga persona posicion meditacion",
        "🧘‍♀|loto yoga mujer posicion meditacion",
        "🧘‍♂|loto yoga hombre posicion meditacion",
        "🧙|maga bruja brujo persona hechicera hechicero",
        "🧙‍♀|maga bruja hechicera",
        "🧙‍♂|mago brujo hechicero",
        "🧚|hada puck oberon titania campanilla",
        "🧚‍♀|hada mujer titania campanilla",
        "🧚‍♂|hada puck hombre oberon",
        "🧛|muerto dracula vampiro viviente",
        "🧛‍♀|muerta viviente vampiresa",
        "🧛‍♂|hombre muerto dracula vampiro viviente",
        "🧜|sirena triton persona",
        "🧜‍♀|sirena",
        "🧜‍♂|hombre sirena triton",
        "🧝|elfo magico",
        "🧝‍♀|elfa mujer magico",
        "🧝‍♂|elfo hombre magico",
        "🧞|genio lampara",
        "🧞‍♀|genio mujer lampara",
        "🧞‍♂|djinn genio hombre lampara",
        "🧟|zombi muerto viviente",
        "🧟‍♀|mujer zombi muerta viviente caminante",
        "🧟‍♂|zombi hombre muerto viviente caminante",
        "🧠|cerebro inteligente",
        "🧡|corazon emocion naranja",
        "🧢|con gorra visera beisbol",
        "🧣|abrigo cuello bufanda",
        "🧤|mano guantes",
        "🧥|abrigo chaqueton",
        "🧦|pies ropa calcetines",
        "🧧|lai see rojo buena sobre regalo",
        "🧨|fuegos petardo dinamita explosivo artificiales",
        "🧩|pieza pista puzle conectar rompecabezas",
        "🧪|tubo ensayo ciencia quimica quimico experimento",
        "🧫|petri placa biologo cultivo biologia bacterias",
        "🧬|adn gen vida biologo genetica evolucion",
        "🧭|compas brujula magnetico navegacion orientacion",
        "🧮|abaco contar calculo matematicas",
        "🧯|apagar extintor incendio extinguir",
        "🧰|caja armario mecanico herramienta herramientas",
        "🧱|muro pared arcilla cemento ladrillo",
        "🧲|iman atraccion herradura magnetico",
        "🧳|maleta viajar equipaje",
        "🧴|bote crema solar champu protector hidratante",
        "🧵|hilo aguja coser carrete costura",
        "🧶|bola punto tejer croche ovillo",
        "🧷|punk rock panal imperdible",
        "🧸|oso osito juguete peluche",
        "🧹|bruja barrer escoba fregar",
        "🧺|cesta colada picnic cosecha",
        "🧻|papel rollo higienico absorbente",
        "🧼|jabon banarse lavarse jabonera pastilla enjabonarse",
        "🧽|poroso esponja limpiar absorbente",
        "🧾|libros prueba recibo teneduria testimonio contabilidad",
        "🧿|mal ojo nazar turco amuleto talisman",
        "🩰|bale danza bailar ballet zapatillas",
        "🩱|una bano pieza traje banador",
        "🩲|ropa slip bragas banador interior braguitas",
        "🩳|ropa cortos shorts banador bermudas interior",
        "🩴|dedo chancla chinela sandalia chancleta",
        "🩵|azul cian claro celeste corazon",
        "🩶|gris plata corazon pizarra",
        "🩷|amor rosa bonito gustar corazon",
        "🩸|gota donar herida sangre donacion medicina",
        "🩹|tirita aposito",
        "🩺|doctor latido medico corazon medicina estetoscopio",
        "🩻|rayos doctor huesos medico doctora esqueleto",
        "🩼|palo para ayuda baston lesion muleta",
        "🪀|yoyo dieta efecto juguete fluctuar",
        "🪁|volar cometa viento juguete planear",
        "🪂|ala delta volar paravela paracaidas paracaidismo",
        "🪃|bumeran rebotar boomerang",
        "🪄|mago bruja magia magica varita hechicero",
        "🪅|fiesta pinata caballito celebracion",
        "🪆|rusa rusia muneca babushka mamushka matrioska",
        "🪇|agitar brasil musica maracas percusion movimiento",
        "🪈|flauta madera musica viento flautin instrumento",
        "🪉|amor arpa harpa cupido musica orquesta",
        "🪊|jazz metal musica triste viento trombon",
        "🪋|bola roca caida fuego espacio estrella",
        "🪌|goma error borrar quitar dibujar deshacer",
        "🪍|con red cazar malla mango pescar",
        "🪎|oro botin cofre joyas plata valor",
        "🪏|hoyo pala cavar nieve huerto planta",
        "🪐|con anillos planeta saturno saturnino",
        "🪑|silla asiento sentarse",
        "🪒|navaja afeitar afilado barbero afeitado cuchilla",
        "🪓|hacha talar cortar madera dividir hachuela",
        "🪔|diya aceite lampara",
        "🪕|banjo banyo cuerda musica instrumento",
        "🪖|casco guerra militar soldado ejercito guerrero",
        "🪗|acordeon concertina",
        "🪘|conga ritmo tambor tamboril",
        "🪙|oro metal plata dinero moneda tesoro",
        "🪚|talar sierra carpintero carpinteria herramienta",
        "🪛|tornillo herramienta atornillador destornillador",
        "🪜|escalar escalon peldano escalera escalerilla",
        "🪝|gancho garfio agarrar anzuelo atrapar",
        "🪞|espejo reflejo especulo reflector",
        "🪟|marco vista cristal ventana abertura apertura",
        "🪠|retrete succion servicio fontanero desatascador",
        "🪡|aguja coser hilar punto tejer bordado",
        "🪢|atar nudo anudar enredar trenzar",
        "🪣|cuba cubo balde cubeta barreno",
        "🪤|cebo cepo raton trampa enganar ratones",
        "🪥|dental limpio cepillo dientes higiene servicio",
        "🪦|tumba estela lapida sepulcro cementario",
        "🪧|aviso poste cartel anuncio letrero pancarta",
        "🪨|pena roca piedra penasco pedrusco",
        "🪩|bola disco bailar fiesta brillar espejos",
        "🪪|carne permiso conducir identidad seguridad credenciales",
        "🪫|baja pila carga bateria energia electronico",
        "🪬|mano hamsa jamsa maria fatima miriam",
        "🪭|calor feria airear bailar abanico abierto",
        "🪮|afro pelo peine peineta",
        "🪯|sij sikh khanda sijismo religion",
        "🪰|mal olor bicho mosca basura podrido",
        "🪱|oruga gusano lombriz parasito",
        "🪲|bicho insecto escarabajo",
        "🪳|bicho plaga alimana insecto cucaracha",
        "🪴|crecer maceta planta tiesto",
        "🪵|lena palos madera madero tronco hoguera",
        "🪶|ave pluma ligero pajaro plumaje",
        "🪷|flor loto pureza budismo hinduismo",
        "🪸|coral oceano arrecife",
        "🪹|nido vacio anidar anidacion anidamiento",
        "🪺|con nido anidar huevos anidacion anidamiento",
        "🪻|boca flor lila dragon lupino jacinto",
        "🪼|picar marino medusa picadura invertebrado",
        "🪽|ala ave angel volar pajaro angelical",
        "🪾|sin arbol hojas ramas madera muerto",
        "🪿|ave oca ganso pajaro graznar",
        "🫀|pulso humano latido organo corazon anatomia",
        "🫁|organo exhalar inhalar pulmones respirar respiracion",
        "🫂|adios abrazo saludo gracias personas despedida",
        "🫃|lleno hombre barriga inflado hinchado hinchazon",
        "🫄|barriga persona embarazo gestacion hinchazon embarazada",
        "🫅|con real noble corona monarca persona",
        "🫆|delito huella rastro digital forense dactilar",
        "🫈|yeti bosque peluda peludo bigfoot gigante",
        "🫌|oruga cambio fragil insecto monarca mariposa",
        "🫍|mar orca marino oceano ballena",
        "🫎|alce asta animal ciervo uapiti cuernos",
        "🫏|asno mula burro terco animal borrico",
        "🫐|del azul baya bosque frutos mirtilo",
        "🫑|aji rojo chile morron verdura pimiento",
        "🫒|oliva comida aceituna aperitivo",
        "🫓|pan sin naan pita arepa levadura",
        "🫔|wrap tamal mejicano mexicano",
        "🫕|olla queso suizo fondue chocolate",
        "🫖|bebida tetera infusion",
        "🫗|vaso vacio bebida verter liquido derramar",
        "🫘|roja judia comida judias alubias legumbre",
        "🫙|salsa tarro vacio frasco almacenar condimento",
        "🫚|raiz cerveza especia garganta jengibre",
        "🫛|soja vaina judias edamame verdura guisante",
        "🫜|nabo raiz comida huerto rabano verdura",
        "🫝|pepino salmuera aperitivo encurtido fermentar pepinillo",
        "🫟|tinta gotear mancha liquido manchar pintura",
        "🫠|cara calor liquido fundirse derretido derretirse",
        "🫡|sol cara vale orden saludo ejercito",
        "🫢|con boca cara ojos tapada asombro",
        "🫣|con ojo cara mirar espiar tapada",
        "🫤|con boca cara vaya diagonal inseguro",
        "🫥|con cara linea puntos depresivo deprimido",
        "🫦|labio ligar miedo ansioso mordido incomodo",
        "🫧|agua bajo jabon eructar limpiar burbujas",
        "🫨|cara shock vibrar temblar terremoto temblorosa",
        "🫩|con cara ojos sueno ojeras agotado",
        "🫪|cara panico ansiedad hinchado deformada vulnerable",
        "🫫|cara romper revelar tension desmoronar enmascarar",
        "🫯|nube lucha pelea bronca alboroto altercado",
        "🫰|con amor caro dedo mano dinero",
        "🫱|mano hacia derecha",
        "🫲|mano hacia izquierda",
        "🫳|con mano abajo bajar fuera hacia",
        "🫴|con ven dame mano trae hacia",
        "🫵|dedo indice apuntar apuntandote",
        "🫶|amor manos corazon formando",
        "🫷|esos mano stop choca cinco hacia",
        "🫸|esos mano stop choca cinco hacia",
        "🫹|eso esto hacia pulgar agarrar neutral",
        "🫺|eso esto hacia pulgar agarrar derecha",
    ];
}
