namespace MoneyBack.Web.Services;

/// <summary>
/// Banderas de país con su nombre en español.
///
/// Las anotaciones de Unicode en español no las traen —están en un archivo
/// derivado aparte— así que escribir "México" o "Japón" no encontraba nada,
/// justo lo que alguien teclea cuando ahorra para un viaje.
/// </summary>
public static class EmojisBanderas
{
    public static readonly string[] Entradas =
    [
        "🇦🇩|andorra bandera pais",
        "🇦🇪|emiratos dubai bandera pais",
        "🇦🇷|argentina bandera pais",
        "🇦🇹|austria bandera pais",
        "🇦🇺|australia bandera pais",
        "🇧🇪|belgica bandera pais",
        "🇧🇴|bolivia bandera pais",
        "🇧🇷|brasil bandera pais",
        "🇨🇦|canada bandera pais",
        "🇨🇭|suiza bandera pais",
        "🇨🇱|chile bandera pais",
        "🇨🇳|china bandera pais",
        "🇨🇴|colombia bandera pais",
        "🇨🇷|costa rica bandera pais",
        "🇨🇺|cuba bandera pais",
        "🇨🇿|chequia praga bandera pais",
        "🇩🇪|alemania bandera pais",
        "🇩🇰|dinamarca bandera pais",
        "🇩🇴|republica dominicana bandera pais",
        "🇪🇨|ecuador bandera pais",
        "🇪🇬|egipto bandera pais",
        "🇪🇸|espana bandera pais",
        "🇫🇮|finlandia bandera pais",
        "🇫🇷|francia paris bandera pais",
        "🇬🇧|reino unido inglaterra londres bandera pais",
        "🇬🇷|grecia bandera pais",
        "🇬🇹|guatemala bandera pais",
        "🇭🇳|honduras bandera pais",
        "🇭🇷|croacia bandera pais",
        "🇭🇺|hungria bandera pais",
        "🇮🇩|indonesia bandera pais",
        "🇮🇪|irlanda bandera pais",
        "🇮🇱|israel bandera pais",
        "🇮🇳|india bandera pais",
        "🇮🇸|islandia bandera pais",
        "🇮🇹|italia roma bandera pais",
        "🇯🇵|japon bandera pais",
        "🇰🇪|kenia bandera pais",
        "🇰🇷|corea bandera pais",
        "🇲🇦|marruecos bandera pais",
        "🇲🇽|mexico bandera pais",
        "🇲🇾|malasia bandera pais",
        "🇳🇬|nigeria bandera pais",
        "🇳🇮|nicaragua bandera pais",
        "🇳🇱|holanda paises bajos bandera pais",
        "🇳🇴|noruega bandera pais",
        "🇳🇿|nueva zelanda bandera pais",
        "🇵🇦|panama bandera pais",
        "🇵🇪|peru bandera pais",
        "🇵🇭|filipinas bandera pais",
        "🇵🇱|polonia bandera pais",
        "🇵🇷|puerto rico bandera pais",
        "🇵🇹|portugal bandera pais",
        "🇵🇾|paraguay bandera pais",
        "🇷🇴|rumania bandera pais",
        "🇷🇺|rusia bandera pais",
        "🇸🇦|arabia bandera pais",
        "🇸🇪|suecia bandera pais",
        "🇸🇬|singapur bandera pais",
        "🇸🇻|salvador bandera pais",
        "🇹🇭|tailandia bandera pais",
        "🇹🇷|turquia bandera pais",
        "🇺🇸|estados unidos usa eeuu bandera pais",
        "🇺🇾|uruguay bandera pais",
        "🇻🇪|venezuela bandera pais",
        "🇻🇳|vietnam bandera pais",
        "🇿🇦|sudafrica bandera pais",
    ];
}
